######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 6 15:08:40 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += mainwindow.h surfaceviewer.h
SOURCES += main.cpp mainwindow.cpp surfaceviewer.cpp
RESOURCES += surfaceviewer.qrc

